import { execSync } from "node:child_process";

import { ConfigEnv, PluginOption, UserConfig } from "vite";

const PLUGIN_NAME = "vite-elm-plugin";

type DefaultUserConfigOptions = {
  /** Receives the mode from {@link ConfigEnv}. */
  mode: string;

  /** The JavaScript output generated by the Elm compiler.  */
  elmCompiledJs: string;

  isWatchMode: boolean;
};

function buildDefaultUserConfigForElm({ mode, elmCompiledJs, isWatchMode }: DefaultUserConfigOptions): UserConfig {
  const toExclude = ["**/elm-stuff/**", elmCompiledJs];

  const server = isWatchMode ? { watch: { ignored: toExclude } } : {};
  const buildWatch = isWatchMode ? { watch: { exclude: toExclude } } : {};

  return {
    /**
     * Considers this path to be the root of the server, avoiding relative ones
     * that starts with `/`, like `/assets/icon.svg`.
     */
    base: "./",

    /**
     * Avoids clearning the screen between compilations.
     */
    clearScreen: false,

    /**
     * Options for the Vite development server, i.e., `vite`.
     */
    server,

    /**
     * Options for `vite build`. `--watch` will only apply when running `vite build --watch`.
     */
    build: {
      emptyOutDir: true,
      ...buildWatch,
    },

    define: {
      __IS_DEV_MODE__: mode === "development",
    },
  };
}

type ElmCompilerPluginOptions = {
  elmInputMain?: string;
  elmJsOutputTo?: string;
  shouldOptimizeOutput?: boolean;
  ignoreElm?: boolean;
  extraConfigs?: Pick<UserConfig, "build">;
};

type ElmMakeCommandOptions = {
  elmMakeInput: string;
  elmMakeOutput: string;
  shouldOptimize: boolean;
};

export function elmMakeCommand(opts: ElmMakeCommandOptions): string {
  const { elmMakeInput, elmMakeOutput, shouldOptimize } = opts;

  let command = `
      elm make ${elmMakeInput} --output=${elmMakeOutput} ${shouldOptimize ? "--optimize" : ""} \\
      && sed -i -E -e 's/\\(this\\)/(window)/g' ${elmMakeOutput}
  `;

  return command;
}

export function elmCompilerPlugin({
  elmInputMain = "src/Main.elm",
  elmJsOutputTo = "compiled.js",
  shouldOptimizeOutput = false,
  ignoreElm = false,
  extraConfigs = {},
}: ElmCompilerPluginOptions = {}): PluginOption {
  // Check if `vite build --watch` is being used
  let isWatchMode = process.argv.includes("--watch");
  let shouldOptimize = shouldOptimizeOutput;
  console.log("isWatchMode", isWatchMode);
  console.log("shouldOptimize", shouldOptimize);

  const plugin: PluginOption = {
    name: PLUGIN_NAME,

    // Set default Vite options like 'base' and others
    config(config, { command, mode }: ConfigEnv) {
      // Enable optimization only for regular production builds
      if (command === "build" && !isWatchMode) {
        shouldOptimize = true;
      } else {
        shouldOptimize = false; // Disable optimization for development and watch mode
      }

      let defaultConfig = buildDefaultUserConfigForElm({ mode, elmCompiledJs: elmJsOutputTo, isWatchMode });

      if (extraConfigs.build) {
        defaultConfig.build = { ...defaultConfig.build, ...extraConfigs.build };
      }

      return defaultConfig;
    },

    // Handle initial build and `vite build --watch`
    async buildStart() {
      if (ignoreElm) {
        console.log("Ignoring Elm changes.");
        return;
      }

      try {
        console.log("Starting Elm compilation...");

        execSync(
          elmMakeCommand({
            elmMakeInput: elmInputMain,
            elmMakeOutput: elmJsOutputTo,
            shouldOptimize,
          }),
          { stdio: "inherit" },
        );

        console.log("Elm compilation finished.");
      } catch (err: any) {
        console.error("Elm compilation error:", err.stderr);
        throw new Error("Failed to compile Elm files.");
      } finally {
        console.log("Elm build process completed.");
      }
    },

    // Handle file changes in watch mode (like `vite build --watch`)
    async watchChange(file: string) {
      if (ignoreElm) {
        console.log("Ignoring Elm changes.");
        return;
      }

      if (file.endsWith(".elm")) {
        try {
          execSync(
            elmMakeCommand({
              elmMakeInput: elmInputMain,
              elmMakeOutput: elmJsOutputTo,
              shouldOptimize: shouldOptimizeOutput,
            }),
            { stdio: "inherit" },
          );
        } catch (err: any) {
          console.error("Elm compilation error:", err.stderr);
        }
      }
    },
  };

  return plugin;
}
